 "use client";
import {useEffect,useState} from "react";
const CATEGORIES=["Action Sound", "Alarm & Chime", "Ambience", "Animals", "Arcade Noises", "Beep", "Bell", "Bugs", "build up", "Button", "Camera", "Chime", "Clicks", "clock", "Construction & Tools", "Crowd & People", "Digital", "Electric", "Epic Cinematic Trailer Impact - Pack 2", "error", "ESFX", "Evolve Audio - Epic Drama SFX", "Evolve Audio - Essential Transitions FREE", "Explosions", "Fart", "Feeling", "Fire & Fireworks", "Firearms", "Food", "FW sounds", "Games", "Gear", "Glitch", "Hits", "Horn", "i phone", "Keyboard & Mouse", "knife", "liquid", "Logo Animation", "Mechanical", "Meme SFX", "Miscellaneous", "Money", "Musical", "Negative", "Notifications", "other", "Paper Sound Effects", "pen click", "Percussion", "Phone", "Positive", "Ringtones", "Risers", "Sci-Fi", "shining", "Sports", "Swishes", "Switch", "Swoosh", "Tone", "Ui Sound", "Vehicles", "Vibes", "Water", "Wind", "Wooshes", "Unorganised", "Alien", "Arcade", "Bolt", "Bowling", "Brick", "Broom", "Bubbles", "Cable", "Cards", "Cartoon", "Cartoonish", "Chain", "Chalkboard", "Champagne", "Coin", "Crash", "Creak", "Dice", "Discord", "Door", "Drawer", "Duffle Bag", "DVD & CD", "Electric Timer", "Golf", "Hatch", "Hinge", "Lego", "Light", "Magic", "Marker", "Metal", "Mud", "Paper & book", "Pay Phone", "PC Mouse", "Pen", "Poker Chips", "Pop", "Punch", "Radio", "Register", "Roblox", "Spongebob", "Writing"];
type Sound={id:number,title:string,category:string,description:string,file_url:string,trending:boolean};
export default function Home(){
 const [tab,setTab]=useState("home"),[cat,setCat]=useState(""),[sounds,setSounds]=useState<Sound[]>([]),[search,setSearch]=useState(""),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
 async function load(c=cat,t=tab,q=search){setBusy(true);let p=new URLSearchParams();if(c)p.set("category",c);if(t==="trending")p.set("trending","true");if(q)p.set("search",q);let r=await fetch("/api/sounds?"+p);setSounds(await r.json());setBusy(false)}
 useEffect(()=>{if(tab!=="upload")load("",tab,"")},[tab,cat]);
 async function upload(e:any){e.preventDefault();setMsg("");setBusy(true);let fd=new FormData(e.currentTarget);fd.set("trending",fd.get("trending")?"true":"false");let r=await fetch("/api/sounds",{method:"POST",body:fd}),d=await r.json();setBusy(false);if(!r.ok){setMsg(d.error||"Upload failed");return}setMsg("Uploaded successfully!");e.currentTarget.reset()}
 const open=(c:string)=>{setCat(c);setTab("categories")};
 return <><header className="header"><nav className="nav"><div className="logo">SFXVault</div><button onClick={()=>{setTab("home");setCat("")}}>Home</button><button onClick={()=>{setTab("categories");setCat("")}}>Categories ({CATEGORIES.length})</button><button onClick={()=>{setTab("trending");setCat("")}}>Trending 🔥</button><button className="uploadBtn" onClick={()=>setTab("upload")}>Upload</button></nav></header><main className="container">
 {tab==="home"&&<section className="hero"><h1>Find the perfect sound for your edit</h1><p className="muted">Browse categories and trending sound effects.</p><div className="toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load("","home",search)} placeholder="Search sounds..."/><button className="primary" onClick={()=>load("","home",search)}>Search</button></div><h2>Categories</h2><div className="grid">{CATEGORIES.slice(0,16).map(c=><div className="card category" key={c} onClick={()=>open(c)}>{c}</div>)}</div></section>}
 {tab==="categories"&&<section><h1>{cat||"Categories"}</h1>{!cat?<div className="grid">{CATEGORIES.map(c=><div className="card category" key={c} onClick={()=>open(c)}>{c}</div>)}</div>:<><button onClick={()=>setCat("")}>← All Categories</button><SoundList sounds={sounds} busy={busy}/></>}</section>}
 {tab==="trending"&&<section><h1>Trending 🔥</h1><p className="muted">Only sounds marked Trending during upload appear here.</p><SoundList sounds={sounds} busy={busy}/></section>}
 {tab==="upload"&&<section className="form"><h1>Upload Sound</h1><form onSubmit={upload}><input name="title" placeholder="Sound title" required/><select name="category" required defaultValue=""><option value="" disabled>Select category</option>{CATEGORIES.map(c=><option key={c} value={c}>{c}</option>)}</select><textarea name="description" placeholder="Description (optional)" rows={3}/><input name="file" type="file" accept="audio/*" required/><label className="checkbox"><input name="trending" type="checkbox"/> Mark as Trending 🔥</label><button className="primary" disabled={busy}>{busy?"Uploading...":"Upload Sound"}</button></form>{msg&&<p className={msg.includes("success")?"success":"error"}>{msg}</p>}</section>}
 </main></>
}
function SoundList({sounds,busy}:{sounds:Sound[],busy:boolean}){if(busy)return <p>Loading...</p>;if(!sounds.length)return <p className="muted">No sounds found.</p>;return <div className="grid">{sounds.map(s=><div className="card sound" key={s.id}><b>{s.title} {s.trending&&<span className="badge">🔥 Trending</span>}</b><span className="muted">{s.category}</span>{s.description&&<p className="muted">{s.description}</p>}<audio controls src={s.file_url}/><a className="primary" href={s.file_url} download>Download</a></div>)}</div>}
